Resources:
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # Generate a name based on the stage
      TableName: ${self:custom.stage}-orders
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:provider.dynamodb.throughput}
        WriteCapacityUnits: ${self:provider.dynamodb.throughput}

# Print out the name of the table that is created
Outputs:
  OrdersTableName:
    Value:
      Ref: OrdersTable
