Resources:
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # Generate a name based on the stage
      TableName: ${self:custom.stage}-orders
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: financialStatus
          AttributeType: S
        - AttributeName: paidAt
          AttributeType: S
        - AttributeName: fulfillmentStatus
          AttributeType: S
        - AttributeName: fulfilledAt
          AttributeType: S
        - AttributeName: currency
          AttributeType: S
        - AttributeName: subtotal
          AttributeType: S
        - AttributeName: shippingCost
          AttributeType: S
        - AttributeName: taxes
          AttributeType: S
        - AttributeName: amount
          AttributeType: S
        - AttributeName: refunded
          AttributeType: S
        - AttributeName: total
          AttributeType: S
        - AttributeName: discountCode
          AttributeType: S
        - AttributeName: discountAmount
          AttributeType: S
        - AttributeName: shippingMethod
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: cancelledAt
          AttributeType: S
        - AttributeName: privateNotes
          AttributeType: S
        - AttributeName: paymentMethod
          AttributeType: S
        - AttributeName: paymentReference
          AttributeType: S
        - AttributeName: lineItemQuantity
          AttributeType: S
        - AttributeName: lineItemName
          AttributeType: S
        - AttributeName: lineItemPrice
          AttributeType: S
        - AttributeName: lineItemSku
          AttributeType: S
        - AttributeName: lineItemVariant
          AttributeType: S
        - AttributeName: lineItemRequiresShipping
          AttributeType: S
        - AttributeName: lineItemTaxable
          AttributeType: S
        - AttributeName: lineItemFulfillmentStatus
          AttributeType: S
        # customer data
        - AttributeName: email
          AttributeType: S
        - AttributeName: billingName
          AttributeType: S
        - AttributeName: billingAddress1
          AttributeType: S
        - AttributeName: billingAddress2
          AttributeType: S
        - AttributeName: billingCity
          AttributeType: S
        - AttributeName: billingZip
          AttributeType: S
        - AttributeName: billingProvince
          AttributeType: S
        - AttributeName: billingCountry
          AttributeType: S
        - AttributeName: billingPhone
          AttributeType: S
        - AttributeName: shippingName
          AttributeType: S
        - AttributeName: shippingAddress1
          AttributeType: S
        - AttributeName: shippingAddress2
          AttributeType: S
        - AttributeName: shippingCity
          AttributeType: S
        - AttributeName: shippingZip
          AttributeType: S
        - AttributeName: shippingProvince
          AttributeType: S
        - AttributeName: shippingCountry
          AttributeType: S
        - AttributeName: shippingPhone
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
