module.exports = [
  {
     "id":"1",
     "email":"dave.painter.coffee@gmail.com",
     "financialStatus":"PAID",
     "paidAt":"7/25/2018 21:06",
     "fulfillmentStatus":"pending",
     "fulfilledAt":"",
     "currency":"USD",
     "subtotal":"20",
     "shipping":"10",
     "taxes":"0",
     "amountRefunded":"0",
     "total":"30",
     "discountCode":"",
     "discountAmount":"0",
     "shippingMethod":"Flat rate",
     "createdAt":"7/25/2018 21:06",
     "lineItemQuantity":"1",
     "lineItemName":"Washed Colombian Coffee",
     "lineItemPrice":"10",
     "lineItemSku":"SQ0509144",
     "lineItemVariant":"200g",
     "lineItemRequiresShipping":"TRUE",
     "lineItemTaxable":"TRUE",
     "lineItemFulfillmentStatus":"pending",
     "billingName":"Dave Painter",
     "billingAddress1":"1456 Brush Blvd",
     "billingAddress2":"",
     "billingCity":"Brightenwood",
     "billingZip":"95076",
     "billingProvince":"CA",
     "billingCountry":"United States",
     "billingPhone":"",
     "shippingName":"Dave Painter",
     "shippingAddress1":"1456 Brush Blvd",
     "shippingAddress2":"",
     "shippingCity":"Brightenwood",
     "shippingZip":"95076",
     "shippingProvince":"CA",
     "shippingCountry":"United States",
     "shippingPhone":"",
     "cancelledAt":"",
     "privateNotes":"",
     "paymentMethod":"Stripe",
     "paymentReference":"ch_1Cs0jnLjGdjc8rbZ4qjuMRNp"
  },
  {
     "id":"1",
     "email":"",
     "financialStatus":"",
     "paidAt":"",
     "Fulfillment Status":"",
     "Fulfilled at":"",
     "currency":"",
     "subtotal":"",
     "shipping":"",
     "taxes":"",
     "amountRefunded":"",
     "total":"",
     "discountCode":"",
     "discountAmount":"",
     "shippingMethod":"",
     "createdAt":"",
     "lineItemQuantity":"1",
     "lineItemName":"Washed Ethiopian Coffee",
     "lineItemPrice":"10",
     "lineItemSku":"SQ0030016",
     "lineItemVariant":"200g",
     "lineItemRequiresShipping":"TRUE",
     "lineItemTaxable":"TRUE",
     "lineItemFulfillmentStatus":"pending",
     "billingName":"",
     "billingAddress1":"",
     "billingAddress2":"",
     "billingCity":"",
     "billingZip":"",
     "billingProvince":"",
     "billingCountry":"",
     "billingPhone":"",
     "shippingName":"",
     "shippingAddress1":"",
     "shippingAddress2":"",
     "shippingCity":"",
     "shippingZip":"",
     "shippingProvince":"",
     "shippingCountry":"",
     "shippingPhone":"",
     "cancelledAt":"",
     "privateNotes":"",
     "paymentMethod":"",
     "paymentReference":""
  },
  {
     "id":"2",
     "email":"rob.boss@yahoo.com",
     "financialStatus":"refunded",
     "paidAt":"7/25/2018 22:12",
     "Fulfillment Status":"cancelled",
     "Fulfilled at":"",
     "currency":"USD",
     "subtotal":"10",
     "shipping":"10",
     "taxes":"0",
     "amountRefunded":"20",
     "total":"20",
     "discountCode":"",
     "discountAmount":"0",
     "shippingMethod":"Flat rate",
     "createdAt":"7/25/2018 22:12",
     "lineItemQuantity":"1",
     "lineItemName":"Washed Guatemalan Coffee",
     "lineItemPrice":"10",
     "lineItemSku":"SQ9095169",
     "lineItemVariant":"200g",
     "lineItemRequiresShipping":"TRUE",
     "lineItemTaxable":"TRUE",
     "lineItemFulfillmentStatus":"cancelled",
     "billingName":"Rob Boss",
     "billingAddress1":"123 Happy Tree St.",
     "billingAddress2":"",
     "billingCity":"Detroit",
     "billingZip":"97214",
     "billingProvince":"OR",
     "billingCountry":"United States",
     "billingPhone":"8583350579",
     "shippingName":"Rob Boss",
     "shippingAddress1":"123 Happy Tree St.",
     "shippingAddress2":"",
     "shippingCity":"Detroit",
     "shippingZip":"97214",
     "shippingProvince":"OR",
     "shippingCountry":"United States",
     "shippingPhone":"5552340789",
     "cancelledAt":"7/26/2018 12:32",
     "privateNotes":"",
     "paymentMethod":"Stripe",
     "paymentReference":"ch_1Cs1mILjGdjc8rbZPDKev2eP"
  },
  {
     "id":"3",
     "email":"cavepaintercoffee@gmail.com",
     "financialStatus":"PAID",
     "paidAt":"8/4/2018 19:26",
     "Fulfillment Status":"pending",
     "Fulfilled at":"",
     "currency":"USD",
     "subtotal":"240",
     "shipping":"0",
     "taxes":"0",
     "amountRefunded":"0",
     "total":"240",
     "discountCode":"",
     "discountAmount":"0",
     "shippingMethod":"",
     "createdAt":"8/4/2018 19:26",
     "lineItemQuantity":"1",
     "lineItemName":"3 month subscription",
     "lineItemPrice":"240",
     "lineItemSku":"SQ7673338",
     "lineItemVariant":"400g/2/Every other week",
     "lineItemRequiresShipping":"FALSE",
     "lineItemTaxable":"TRUE",
     "lineItemFulfillmentStatus":"pending",
     "billingName":"Cave Painter",
     "billingAddress1":"49 Northeast 7th Square",
     "billingAddress2":"",
     "billingCity":"Portland",
     "billingZip":"97211",
     "billingProvince":"OR",
     "billingCountry":"United States",
     "billingPhone":"",
     "shippingName":"Cave Painter",
     "shippingAddress1":"",
     "shippingAddress2":"",
     "shippingCity":"",
     "shippingZip":"",
     "shippingProvince":"",
     "shippingCountry":"",
     "shippingPhone":"",
     "cancelledAt":"",
     "privateNotes":"",
     "paymentMethod":"Stripe",
     "paymentReference":"ch_1CvbxKLjGdjc8rbZOw3r6oT0"
  },
  {
     "id":"4",
     "email":"cavepaintercoffee@gmail.com",
     "financialStatus":"PAID",
     "paidAt":"8/4/2018 19:28",
     "Fulfillment Status":"pending",
     "Fulfilled at":"",
     "currency":"USD",
     "subtotal":"40",
     "shipping":"10",
     "taxes":"0",
     "amountRefunded":"0",
     "total":"50",
     "discountCode":"",
     "discountAmount":"0",
     "shippingMethod":"Flat rate",
     "createdAt":"8/4/2018 19:28",
     "lineItemQuantity":"1",
     "lineItemName":"Washed Colombian Coffee",
     "lineItemPrice":"10",
     "lineItemSku":"SQ0509144",
     "lineItemVariant":"200g",
     "lineItemRequiresShipping":"TRUE",
     "lineItemTaxable":"TRUE",
     "lineItemFulfillmentStatus":"pending",
     "billingName":"cave painter",
     "billingAddress1":"49 Northeast 7th Square",
     "billingAddress2":"",
     "billingCity":"Portland",
     "billingZip":"97211",
     "billingProvince":"OR",
     "billingCountry":"United States",
     "billingPhone":"",
     "shippingName":"cave painter",
     "shippingAddress1":"49 Northeast 7th Square",
     "shippingAddress2":"",
     "shippingCity":"Portland",
     "shippingZip":"97211",
     "shippingProvince":"OR",
     "shippingCountry":"United States",
     "shippingPhone":"",
     "cancelledAt":"",
     "privateNotes":"",
     "paymentMethod":"Stripe",
     "paymentReference":"ch_1CvbyjLjGdjc8rbZKEVHb7k7"
  },
  {
     "id":"4",
     "email":"",
     "financialStatus":"",
     "paidAt":"",
     "Fulfillment Status":"",
     "Fulfilled at":"",
     "currency":"",
     "subtotal":"",
     "shipping":"",
     "taxes":"",
     "amountRefunded":"",
     "total":"",
     "discountCode":"",
     "discountAmount":"",
     "shippingMethod":"",
     "createdAt":"",
     "lineItemQuantity":"1",
     "lineItemName":"3 month subscription",
     "lineItemPrice":"30",
     "lineItemSku":"SQ7103073",
     "lineItemVariant":"200g/1/Monthly",
     "lineItemRequiresShipping":"FALSE",
     "lineItemTaxable":"TRUE",
     "lineItemFulfillmentStatus":"pending",
     "billingName":"",
     "billingAddress1":"",
     "billingAddress2":"",
     "billingCity":"",
     "billingZip":"",
     "billingProvince":"",
     "billingCountry":"",
     "billingPhone":"",
     "shippingName":"",
     "shippingAddress1":"",
     "shippingAddress2":"",
     "shippingCity":"",
     "shippingZip":"",
     "shippingProvince":"",
     "shippingCountry":"",
     "shippingPhone":"",
     "cancelledAt":"",
     "privateNotes":"",
     "paymentMethod":"",
     "paymentReference":""
  }
]
